# Generated by Django 2.2.6 on 2020-12-01 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('gpu', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text='Controls whether docker image can be selected by non-staff users')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True, help_text='Controls whether submissions are currently accepted')),
                ('hidden', models.BooleanField(default=False, help_text='Controls whether leaderboard is revealed or not')),
                ('cpu', models.IntegerField(default=2, help_text='Number of CPUs provided to the decoder')),
                ('memory', models.IntegerField(default=12000, help_text='Amount of memory provided to the decoder (MB)')),
                ('timeout', models.IntegerField(default=36000, help_text='Time provided to the decoder (seconds)')),
                ('decoder_fixed', models.BooleanField(default=False, help_text='Only allow already submitted decoders to be resubmitted')),
                ('decoder_size_limit', models.BigIntegerField(blank=True, help_text='Optional limit of decoder size (bytes)', null=True)),
                ('data_size_limit', models.BigIntegerField(blank=True, help_text='Optional limit of encoded data size (bytes)', null=True)),
                ('total_size_limit', models.BigIntegerField(blank=True, help_text='Optional limit of combined file size (bytes)', null=True)),
                ('data_fraction', models.FloatField(blank=True, help_text='Fraction of complete dataset (used to estimate total dataset size)', null=True)),
                ('settings', jsonfield.fields.JSONField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('decoder_hash', models.CharField(max_length=128)),
                ('decoder_size', models.IntegerField()),
                ('decoding_time', models.IntegerField(blank=True, null=True)),
                ('data_size', models.IntegerField()),
                ('hidden', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Error'), (10, 'Waiting'), (20, 'Decoding'), (30, 'Decoding failed'), (40, 'Decoded'), (50, 'Evaluating'), (60, 'Evaluation failed'), (70, 'Success'), (80, 'Canceled')], default=10)),
                ('link', models.CharField(blank=True, max_length=512)),
                ('docker_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.DockerImage')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.Phase')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.Task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.Task'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('metric', models.CharField(max_length=128)),
                ('value', models.FloatField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission')),
            ],
        ),
    ]
