# Generated by Django 2.2.6 on 2021-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='ask_permission',
            field=models.BooleanField(default=False, help_text='Ask for permission to publish reconstructions?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='permission',
            field=models.BooleanField(default=False, help_text='Are we allowed to publish reconstructions?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='link',
            field=models.CharField(blank=True, help_text='An optional link to some website', max_length=512),
        ),
    ]
