# Generated by Django 2.2.6 on 2021-03-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20210318_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='ask_permission',
            field=models.CharField(choices=[('no', 'No'), ('optional', 'Yes (optional)'), ('required', 'Yes (required)')], default='no', help_text='Ask for permission to publish reconstructions?', max_length=32),
        ),
    ]
