# Generated by Django 2.2.6 on 2021-01-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20210110_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='affiliation',
            field=models.CharField(blank=True, max_length=256, verbose_name='Affiliation'),
        ),
    ]
