# Generated by Django 2.2.6 on 2021-01-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.CharField(blank=True, help_text='Name of the members in your team, separated by comma (optional)', max_length=1024, verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='team',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Your university, company or other affiliated institution (optional)', max_length=256, verbose_name='Affiliation'),
        ),
    ]
