# Generated by Django 2.2.6 on 2022-01-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20210110_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='paperid',
            field=models.CharField(blank=True, default='', help_text='PaperID for the CLIC CMT. This is a required field. One team per paper ID.', max_length=10, verbose_name='Paper ID'),
        ),
    ]
