apiVersion: batch/v1
kind: Job
metadata:
  name: {{ submission.job_name }}{% if eval_only %}-eval{% endif %}
  labels:
    id: "{{ submission.id }}"
    task: "{{ submission.task.name }}"
    phase: "{{ submission.phase.name }}"
    team: "{{ submission.team.username }}"
spec:
  template:
    metadata:
      labels:
        id: "{{ submission.id }}"
        task: "{{ submission.task.name }}"
        phase: "{{ submission.phase.name }}"
        team: "{{ submission.team.username }}"
    spec:{% if not eval_only %}
      initContainers:
      - name: decode
        image: "gcr.io/clic-392518/decoding:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "{{ submission.phase.memory }}M"
            cpu: {{ submission.phase.cpu }}{% if submission.docker_image.gpu %}
            nvidia.com/gpu: 1{% endif %}
          limits:
            memory: "{{ submission.phase.memory|add:500 }}M"
            cpu: {{ submission.phase.cpu }}{% if submission.docker_image.gpu %}
            nvidia.com/gpu: 1{% endif %}
        command: [
          "python3",
          "/code/decode.py",{% if debug %}
          "--debug",{% endif %}
          "--id", "{{ submission.id }}",
          "--exec_dir", "/var/lib/docker/submissions"]
        securityContext:
          capabilities: {}
          privileged: true
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/var/run/secret/cloud.google.com/service-account.json"
        envFrom:
          - secretRef:
              name: cloudsql-clic2023
          - secretRef:
              name: buckets-clic2023
        volumeMounts:
          - name: clic-sa-key-volume
            mountPath: "/var/run/secret/cloud.google.com"
          - name: docker-sock
            mountPath: "/var/run/docker.sock"
          - name: executable-volume
            mountPath: "/var/lib/docker"
          - name: code-volume
            mountPath: "/code"{% endif %}
      containers:
      - name: evaluate
        image: "gcr.io/clic-392518/evaluation"
        resources:
          requests:
            cpu: 12
            memory: "{{ submission.phase.memory }}M"
            nvidia.com/gpu: 1
          limits:
            memory: "{{ submission.phase.memory|add:8000 }}M"
            cpu: 12
            nvidia.com/gpu: 1
        command: [
          "python3",
          "/code/evaluate.py",{% if debug %}
          "--debug",{% endif %}
          "--id", "{{ submission.id }}"]
        securityContext:
          capabilities: {}
          privileged: true
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/var/run/secret/cloud.google.com/service-account.json"
        envFrom:
          - secretRef:
              name: cloudsql-clic2023
          - secretRef:
              name: buckets-clic2023
        volumeMounts:
          - name: clic-sa-key-volume
            mountPath: "/var/run/secret/cloud.google.com"
          - name: code-volume
            mountPath: "/code"
      restartPolicy: Never
      volumes:
        - name: clic-sa-key-volume
          secret:
            secretName: clic-sa-key
        - name: docker-sock
          hostPath:
            path: "/var/run/docker.sock"
        - name: executable-volume
          hostPath:
            path: "/var/lib/docker"
        - name: code-volume
          configMap:
            name: code-clic2023
  backoffLimit: 0
