# Generated by Django 2.2.6 on 2019-12-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short name used to identify the schedule', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('custom', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clic.Schedule')),
            ],
        ),
    ]
