# Generated by Django 2.2.6 on 2020-12-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['datetime']},
        ),
    ]
