#!/usr/bin/env python3

from PIL import Image
from glob import glob
from zipfile import ZipFile

FILES_ZIP = 'outputs.zip'    
with ZipFile(FILES_ZIP) as zipfile:
	zipfile.extractall()

for image_file in glob('**/*.jpg', recursive=True):
	print('Decoding ' + image_file)
	Image.open(image_file).save(image_file[:-3] + 'png')
