#!/bin/zsh
# Targeted for about 0.150 bpp right now

mkdir -p valid_encoded;

for src in valid/*.png; do
	target=$(basename "${src/.png/.jpg}");
	target="valid_encoded/${target}";
	convert "${src}" -sampling-factor "4:2:0" -quality 8 "${target}";
done

for src in valid/*.png; do
	# Update total number of bytes here for it to correctly resize.
	# May need to update the lower quality below as well.
	if [ $(python file_size.py) -lt 3239424 ];
		then break;
	fi
	target=$(basename "${src/.png/.jpg}");
	target="valid_encoded/${target}";
	convert "${src}" -sampling-factor "4:2:0" -quality 7 "${target}";
done
