apiVersion: apps/v1
kind: Deployment
metadata:
  name: clic
  labels:
    app: clic
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: clic
    spec:
      containers:
      - name: clic-app
        image: gcr.io/clic-215616/web@{{ DIGEST }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1G"
            cpu: 1
          limits:
            memory: "4G"
            cpu: 4
        command: [
            "gunicorn",
            "--bind", ":8080",
            "--worker-class", "gevent",
            "--workers", "12",
            "--timeout", "600",
            "--log-level", "DEBUG",
            "clic.wsgi"]
        env:
          - name: DB_HOST
            value: "127.0.0.1"
          - name: DB_PORT
            value: "5432"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-clic2020
                key: secret_key
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: sentry-clic2020
                key: dsn
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/var/run/secret/cloud.google.com/service-account.json"
        envFrom:
          - secretRef:
              name: cloudsql-clic2020
          - secretRef:
              name: buckets-clic2020
        volumeMounts:
          - name: clic-sa-key-volume
            mountPath: "/var/run/secret/cloud.google.com"
            readOnly: true
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1

      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        command: ["/cloud_sql_proxy", "-dir=/cloudsql", "-instances=$(DB_INSTANCE)=tcp:5432"]
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/var/run/secret/cloud.google.com/service-account.json"
        envFrom:
          - secretRef:
              name: cloudsql
        volumeMounts:
          - name: clic-sa-key-volume
            mountPath: "/var/run/secret/cloud.google.com"
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
            readOnly: true
          - name: cloudsql
            mountPath: /cloudsql

      volumes:
        - name: clic-sa-key-volume
          secret:
            secretName: clic-sa-key
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
  selector:
    matchLabels:
      app: clic

---

apiVersion: v1
kind: Service
metadata:
  name: clic
  labels:
    app: clic
spec:
  type: LoadBalancer
  loadBalancerIP: "{{ IP_ADDRESS }}"
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: clic
